// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v3.20.3
// source: protos.proto

package messages

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TerminatedReason int32

const (
	TerminatedReason_Stopped           TerminatedReason = 0
	TerminatedReason_AddressTerminated TerminatedReason = 1
	TerminatedReason_NotFound          TerminatedReason = 2
)

// Enum value maps for TerminatedReason.
var (
	TerminatedReason_name = map[int32]string{
		0: "Stopped",
		1: "AddressTerminated",
		2: "NotFound",
	}
	TerminatedReason_value = map[string]int32{
		"Stopped":           0,
		"AddressTerminated": 1,
		"NotFound":          2,
	}
)

func (x TerminatedReason) Enum() *TerminatedReason {
	p := new(TerminatedReason)
	*p = x
	return p
}

func (x TerminatedReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TerminatedReason) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_proto_enumTypes[0].Descriptor()
}

func (TerminatedReason) Type() protoreflect.EnumType {
	return &file_protos_proto_enumTypes[0]
}

func (x TerminatedReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TerminatedReason.Descriptor instead.
func (TerminatedReason) EnumDescriptor() ([]byte, []int) {
	return file_protos_proto_rawDescGZIP(), []int{0}
}

type Weights struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Conv1Weight []*Conv1Weight `protobuf:"bytes,1,rep,name=conv1_weight,json=conv1Weight,proto3" json:"conv1_weight,omitempty"`
	Conv1Bias   []float64      `protobuf:"fixed64,2,rep,packed,name=conv1_bias,json=conv1Bias,proto3" json:"conv1_bias,omitempty"`
	Conv2Weight []*Conv1Weight `protobuf:"bytes,3,rep,name=conv2_weight,json=conv2Weight,proto3" json:"conv2_weight,omitempty"`
	Conv2Bias   []float64      `protobuf:"fixed64,4,rep,packed,name=conv2_bias,json=conv2Bias,proto3" json:"conv2_bias,omitempty"`
	Fc1Weight   []*FcWeight    `protobuf:"bytes,5,rep,name=fc1_weight,json=fc1Weight,proto3" json:"fc1_weight,omitempty"`
	Fc1Bias     []float64      `protobuf:"fixed64,6,rep,packed,name=fc1_bias,json=fc1Bias,proto3" json:"fc1_bias,omitempty"`
	Fc2Weight   []*FcWeight    `protobuf:"bytes,7,rep,name=fc2_weight,json=fc2Weight,proto3" json:"fc2_weight,omitempty"`
	Fc2Bias     []float64      `protobuf:"fixed64,8,rep,packed,name=fc2_bias,json=fc2Bias,proto3" json:"fc2_bias,omitempty"`
}

func (x *Weights) Reset() {
	*x = Weights{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Weights) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Weights) ProtoMessage() {}

func (x *Weights) ProtoReflect() protoreflect.Message {
	mi := &file_protos_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Weights.ProtoReflect.Descriptor instead.
func (*Weights) Descriptor() ([]byte, []int) {
	return file_protos_proto_rawDescGZIP(), []int{0}
}

func (x *Weights) GetConv1Weight() []*Conv1Weight {
	if x != nil {
		return x.Conv1Weight
	}
	return nil
}

func (x *Weights) GetConv1Bias() []float64 {
	if x != nil {
		return x.Conv1Bias
	}
	return nil
}

func (x *Weights) GetConv2Weight() []*Conv1Weight {
	if x != nil {
		return x.Conv2Weight
	}
	return nil
}

func (x *Weights) GetConv2Bias() []float64 {
	if x != nil {
		return x.Conv2Bias
	}
	return nil
}

func (x *Weights) GetFc1Weight() []*FcWeight {
	if x != nil {
		return x.Fc1Weight
	}
	return nil
}

func (x *Weights) GetFc1Bias() []float64 {
	if x != nil {
		return x.Fc1Bias
	}
	return nil
}

func (x *Weights) GetFc2Weight() []*FcWeight {
	if x != nil {
		return x.Fc2Weight
	}
	return nil
}

func (x *Weights) GetFc2Bias() []float64 {
	if x != nil {
		return x.Fc2Bias
	}
	return nil
}

type Conv1Weight struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Conv1Weight []*Conv1Weight2 `protobuf:"bytes,1,rep,name=conv1_weight,json=conv1Weight,proto3" json:"conv1_weight,omitempty"`
}

func (x *Conv1Weight) Reset() {
	*x = Conv1Weight{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Conv1Weight) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Conv1Weight) ProtoMessage() {}

func (x *Conv1Weight) ProtoReflect() protoreflect.Message {
	mi := &file_protos_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Conv1Weight.ProtoReflect.Descriptor instead.
func (*Conv1Weight) Descriptor() ([]byte, []int) {
	return file_protos_proto_rawDescGZIP(), []int{1}
}

func (x *Conv1Weight) GetConv1Weight() []*Conv1Weight2 {
	if x != nil {
		return x.Conv1Weight
	}
	return nil
}

type Conv1Weight2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Conv1Weight []*Conv1Weight3 `protobuf:"bytes,1,rep,name=conv1_weight,json=conv1Weight,proto3" json:"conv1_weight,omitempty"`
}

func (x *Conv1Weight2) Reset() {
	*x = Conv1Weight2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Conv1Weight2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Conv1Weight2) ProtoMessage() {}

func (x *Conv1Weight2) ProtoReflect() protoreflect.Message {
	mi := &file_protos_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Conv1Weight2.ProtoReflect.Descriptor instead.
func (*Conv1Weight2) Descriptor() ([]byte, []int) {
	return file_protos_proto_rawDescGZIP(), []int{2}
}

func (x *Conv1Weight2) GetConv1Weight() []*Conv1Weight3 {
	if x != nil {
		return x.Conv1Weight
	}
	return nil
}

type Conv1Weight3 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Conv1Weight float64 `protobuf:"fixed64,1,opt,name=conv1_weight,json=conv1Weight,proto3" json:"conv1_weight,omitempty"`
}

func (x *Conv1Weight3) Reset() {
	*x = Conv1Weight3{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Conv1Weight3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Conv1Weight3) ProtoMessage() {}

func (x *Conv1Weight3) ProtoReflect() protoreflect.Message {
	mi := &file_protos_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Conv1Weight3.ProtoReflect.Descriptor instead.
func (*Conv1Weight3) Descriptor() ([]byte, []int) {
	return file_protos_proto_rawDescGZIP(), []int{3}
}

func (x *Conv1Weight3) GetConv1Weight() float64 {
	if x != nil {
		return x.Conv1Weight
	}
	return 0
}

type FcWeight struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fc1Weight []*FcWeight2 `protobuf:"bytes,1,rep,name=fc1_weight,json=fc1Weight,proto3" json:"fc1_weight,omitempty"`
}

func (x *FcWeight) Reset() {
	*x = FcWeight{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FcWeight) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FcWeight) ProtoMessage() {}

func (x *FcWeight) ProtoReflect() protoreflect.Message {
	mi := &file_protos_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FcWeight.ProtoReflect.Descriptor instead.
func (*FcWeight) Descriptor() ([]byte, []int) {
	return file_protos_proto_rawDescGZIP(), []int{4}
}

func (x *FcWeight) GetFc1Weight() []*FcWeight2 {
	if x != nil {
		return x.Fc1Weight
	}
	return nil
}

type FcWeight2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fc1Weight float64 `protobuf:"fixed64,1,opt,name=fc1_weight,json=fc1Weight,proto3" json:"fc1_weight,omitempty"`
}

func (x *FcWeight2) Reset() {
	*x = FcWeight2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FcWeight2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FcWeight2) ProtoMessage() {}

func (x *FcWeight2) ProtoReflect() protoreflect.Message {
	mi := &file_protos_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FcWeight2.ProtoReflect.Descriptor instead.
func (*FcWeight2) Descriptor() ([]byte, []int) {
	return file_protos_proto_rawDescGZIP(), []int{5}
}

func (x *FcWeight2) GetFc1Weight() float64 {
	if x != nil {
		return x.Fc1Weight
	}
	return 0
}

type LocalWeights struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Weights *Weights `protobuf:"bytes,1,opt,name=weights,proto3" json:"weights,omitempty"`
}

func (x *LocalWeights) Reset() {
	*x = LocalWeights{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LocalWeights) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalWeights) ProtoMessage() {}

func (x *LocalWeights) ProtoReflect() protoreflect.Message {
	mi := &file_protos_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalWeights.ProtoReflect.Descriptor instead.
func (*LocalWeights) Descriptor() ([]byte, []int) {
	return file_protos_proto_rawDescGZIP(), []int{6}
}

func (x *LocalWeights) GetWeights() *Weights {
	if x != nil {
		return x.Weights
	}
	return nil
}

type RemoteWeights struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Weights *Weights `protobuf:"bytes,1,opt,name=weights,proto3" json:"weights,omitempty"`
}

func (x *RemoteWeights) Reset() {
	*x = RemoteWeights{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoteWeights) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteWeights) ProtoMessage() {}

func (x *RemoteWeights) ProtoReflect() protoreflect.Message {
	mi := &file_protos_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteWeights.ProtoReflect.Descriptor instead.
func (*RemoteWeights) Descriptor() ([]byte, []int) {
	return file_protos_proto_rawDescGZIP(), []int{7}
}

func (x *RemoteWeights) GetWeights() *Weights {
	if x != nil {
		return x.Weights
	}
	return nil
}

type PingMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cnt uint64 `protobuf:"varint,1,opt,name=cnt,proto3" json:"cnt,omitempty"`
}

func (x *PingMessage) Reset() {
	*x = PingMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingMessage) ProtoMessage() {}

func (x *PingMessage) ProtoReflect() protoreflect.Message {
	mi := &file_protos_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingMessage.ProtoReflect.Descriptor instead.
func (*PingMessage) Descriptor() ([]byte, []int) {
	return file_protos_proto_rawDescGZIP(), []int{8}
}

func (x *PingMessage) GetCnt() uint64 {
	if x != nil {
		return x.Cnt
	}
	return 0
}

type PongMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cnt uint64 `protobuf:"varint,1,opt,name=cnt,proto3" json:"cnt,omitempty"`
}

func (x *PongMessage) Reset() {
	*x = PongMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PongMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PongMessage) ProtoMessage() {}

func (x *PongMessage) ProtoReflect() protoreflect.Message {
	mi := &file_protos_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PongMessage.ProtoReflect.Descriptor instead.
func (*PongMessage) Descriptor() ([]byte, []int) {
	return file_protos_proto_rawDescGZIP(), []int{9}
}

func (x *PongMessage) GetCnt() uint64 {
	if x != nil {
		return x.Cnt
	}
	return 0
}

type AggregatorPIDMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AggregatorPID *PID `protobuf:"bytes,1,opt,name=AggregatorPID,proto3" json:"AggregatorPID,omitempty"`
}

func (x *AggregatorPIDMsg) Reset() {
	*x = AggregatorPIDMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AggregatorPIDMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregatorPIDMsg) ProtoMessage() {}

func (x *AggregatorPIDMsg) ProtoReflect() protoreflect.Message {
	mi := &file_protos_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregatorPIDMsg.ProtoReflect.Descriptor instead.
func (*AggregatorPIDMsg) Descriptor() ([]byte, []int) {
	return file_protos_proto_rawDescGZIP(), []int{10}
}

func (x *AggregatorPIDMsg) GetAggregatorPID() *PID {
	if x != nil {
		return x.AggregatorPID
	}
	return nil
}

type OtherCommunicationPIDMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OtherCommPID *PID `protobuf:"bytes,1,opt,name=OtherCommPID,proto3" json:"OtherCommPID,omitempty"`
}

func (x *OtherCommunicationPIDMsg) Reset() {
	*x = OtherCommunicationPIDMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OtherCommunicationPIDMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OtherCommunicationPIDMsg) ProtoMessage() {}

func (x *OtherCommunicationPIDMsg) ProtoReflect() protoreflect.Message {
	mi := &file_protos_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OtherCommunicationPIDMsg.ProtoReflect.Descriptor instead.
func (*OtherCommunicationPIDMsg) Descriptor() ([]byte, []int) {
	return file_protos_proto_rawDescGZIP(), []int{11}
}

func (x *OtherCommunicationPIDMsg) GetOtherCommPID() *PID {
	if x != nil {
		return x.OtherCommPID
	}
	return nil
}

type PID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address   string `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	Id        string `protobuf:"bytes,2,opt,name=Id,proto3" json:"Id,omitempty"`
	RequestId uint32 `protobuf:"varint,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
}

func (x *PID) Reset() {
	*x = PID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PID) ProtoMessage() {}

func (x *PID) ProtoReflect() protoreflect.Message {
	mi := &file_protos_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PID.ProtoReflect.Descriptor instead.
func (*PID) Descriptor() ([]byte, []int) {
	return file_protos_proto_rawDescGZIP(), []int{12}
}

func (x *PID) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *PID) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PID) GetRequestId() uint32 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

// user messages
type PoisonPill struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PoisonPill) Reset() {
	*x = PoisonPill{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PoisonPill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoisonPill) ProtoMessage() {}

func (x *PoisonPill) ProtoReflect() protoreflect.Message {
	mi := &file_protos_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoisonPill.ProtoReflect.Descriptor instead.
func (*PoisonPill) Descriptor() ([]byte, []int) {
	return file_protos_proto_rawDescGZIP(), []int{13}
}

type DeadLetterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Target *PID `protobuf:"bytes,1,opt,name=Target,proto3" json:"Target,omitempty"`
}

func (x *DeadLetterResponse) Reset() {
	*x = DeadLetterResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeadLetterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeadLetterResponse) ProtoMessage() {}

func (x *DeadLetterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeadLetterResponse.ProtoReflect.Descriptor instead.
func (*DeadLetterResponse) Descriptor() ([]byte, []int) {
	return file_protos_proto_rawDescGZIP(), []int{14}
}

func (x *DeadLetterResponse) GetTarget() *PID {
	if x != nil {
		return x.Target
	}
	return nil
}

// system messages
type Watch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Watcher *PID `protobuf:"bytes,1,opt,name=Watcher,proto3" json:"Watcher,omitempty"`
}

func (x *Watch) Reset() {
	*x = Watch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Watch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Watch) ProtoMessage() {}

func (x *Watch) ProtoReflect() protoreflect.Message {
	mi := &file_protos_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Watch.ProtoReflect.Descriptor instead.
func (*Watch) Descriptor() ([]byte, []int) {
	return file_protos_proto_rawDescGZIP(), []int{15}
}

func (x *Watch) GetWatcher() *PID {
	if x != nil {
		return x.Watcher
	}
	return nil
}

type Unwatch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Watcher *PID `protobuf:"bytes,1,opt,name=Watcher,proto3" json:"Watcher,omitempty"`
}

func (x *Unwatch) Reset() {
	*x = Unwatch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Unwatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Unwatch) ProtoMessage() {}

func (x *Unwatch) ProtoReflect() protoreflect.Message {
	mi := &file_protos_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Unwatch.ProtoReflect.Descriptor instead.
func (*Unwatch) Descriptor() ([]byte, []int) {
	return file_protos_proto_rawDescGZIP(), []int{16}
}

func (x *Unwatch) GetWatcher() *PID {
	if x != nil {
		return x.Watcher
	}
	return nil
}

type Terminated struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Who *PID             `protobuf:"bytes,1,opt,name=who,proto3" json:"who,omitempty"`
	Why TerminatedReason `protobuf:"varint,2,opt,name=Why,proto3,enum=messages.TerminatedReason" json:"Why,omitempty"`
}

func (x *Terminated) Reset() {
	*x = Terminated{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Terminated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Terminated) ProtoMessage() {}

func (x *Terminated) ProtoReflect() protoreflect.Message {
	mi := &file_protos_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Terminated.ProtoReflect.Descriptor instead.
func (*Terminated) Descriptor() ([]byte, []int) {
	return file_protos_proto_rawDescGZIP(), []int{17}
}

func (x *Terminated) GetWho() *PID {
	if x != nil {
		return x.Who
	}
	return nil
}

func (x *Terminated) GetWhy() TerminatedReason {
	if x != nil {
		return x.Why
	}
	return TerminatedReason_Stopped
}

type Stop struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Stop) Reset() {
	*x = Stop{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Stop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stop) ProtoMessage() {}

func (x *Stop) ProtoReflect() protoreflect.Message {
	mi := &file_protos_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stop.ProtoReflect.Descriptor instead.
func (*Stop) Descriptor() ([]byte, []int) {
	return file_protos_proto_rawDescGZIP(), []int{18}
}

type Touch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Touch) Reset() {
	*x = Touch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Touch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Touch) ProtoMessage() {}

func (x *Touch) ProtoReflect() protoreflect.Message {
	mi := &file_protos_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Touch.ProtoReflect.Descriptor instead.
func (*Touch) Descriptor() ([]byte, []int) {
	return file_protos_proto_rawDescGZIP(), []int{19}
}

type Touched struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Who *PID `protobuf:"bytes,1,opt,name=who,proto3" json:"who,omitempty"`
}

func (x *Touched) Reset() {
	*x = Touched{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Touched) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Touched) ProtoMessage() {}

func (x *Touched) ProtoReflect() protoreflect.Message {
	mi := &file_protos_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Touched.ProtoReflect.Descriptor instead.
func (*Touched) Descriptor() ([]byte, []int) {
	return file_protos_proto_rawDescGZIP(), []int{20}
}

func (x *Touched) GetWho() *PID {
	if x != nil {
		return x.Who
	}
	return nil
}

var File_protos_proto protoreflect.FileDescriptor

var file_protos_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x22, 0xd7, 0x02, 0x0a, 0x07, 0x57, 0x65, 0x69,
	0x67, 0x68, 0x74, 0x73, 0x12, 0x38, 0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x76, 0x31, 0x5f, 0x77, 0x65,
	0x69, 0x67, 0x68, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x43, 0x6f, 0x6e, 0x76, 0x31, 0x57, 0x65, 0x69, 0x67, 0x68,
	0x74, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x76, 0x31, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x1d,
	0x0a, 0x0a, 0x63, 0x6f, 0x6e, 0x76, 0x31, 0x5f, 0x62, 0x69, 0x61, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x01, 0x52, 0x09, 0x63, 0x6f, 0x6e, 0x76, 0x31, 0x42, 0x69, 0x61, 0x73, 0x12, 0x38, 0x0a,
	0x0c, 0x63, 0x6f, 0x6e, 0x76, 0x32, 0x5f, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x43,
	0x6f, 0x6e, 0x76, 0x31, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x76,
	0x32, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6f, 0x6e, 0x76, 0x32,
	0x5f, 0x62, 0x69, 0x61, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x01, 0x52, 0x09, 0x63, 0x6f, 0x6e,
	0x76, 0x32, 0x42, 0x69, 0x61, 0x73, 0x12, 0x31, 0x0a, 0x0a, 0x66, 0x63, 0x31, 0x5f, 0x77, 0x65,
	0x69, 0x67, 0x68, 0x74, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x46, 0x63, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x52, 0x09,
	0x66, 0x63, 0x31, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x66, 0x63, 0x31,
	0x5f, 0x62, 0x69, 0x61, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x01, 0x52, 0x07, 0x66, 0x63, 0x31,
	0x42, 0x69, 0x61, 0x73, 0x12, 0x31, 0x0a, 0x0a, 0x66, 0x63, 0x32, 0x5f, 0x77, 0x65, 0x69, 0x67,
	0x68, 0x74, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x73, 0x2e, 0x46, 0x63, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x52, 0x09, 0x66, 0x63,
	0x32, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x66, 0x63, 0x32, 0x5f, 0x62,
	0x69, 0x61, 0x73, 0x18, 0x08, 0x20, 0x03, 0x28, 0x01, 0x52, 0x07, 0x66, 0x63, 0x32, 0x42, 0x69,
	0x61, 0x73, 0x22, 0x48, 0x0a, 0x0b, 0x43, 0x6f, 0x6e, 0x76, 0x31, 0x57, 0x65, 0x69, 0x67, 0x68,
	0x74, 0x12, 0x39, 0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x76, 0x31, 0x5f, 0x77, 0x65, 0x69, 0x67, 0x68,
	0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x73, 0x2e, 0x43, 0x6f, 0x6e, 0x76, 0x31, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x32, 0x52,
	0x0b, 0x63, 0x6f, 0x6e, 0x76, 0x31, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x22, 0x49, 0x0a, 0x0c,
	0x43, 0x6f, 0x6e, 0x76, 0x31, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x32, 0x12, 0x39, 0x0a, 0x0c,
	0x63, 0x6f, 0x6e, 0x76, 0x31, 0x5f, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x43, 0x6f,
	0x6e, 0x76, 0x31, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x33, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x76,
	0x31, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x22, 0x31, 0x0a, 0x0c, 0x43, 0x6f, 0x6e, 0x76, 0x31,
	0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x33, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x76, 0x31,
	0x5f, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0b, 0x63,
	0x6f, 0x6e, 0x76, 0x31, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x22, 0x3e, 0x0a, 0x08, 0x46, 0x63,
	0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x32, 0x0a, 0x0a, 0x66, 0x63, 0x31, 0x5f, 0x77, 0x65,
	0x69, 0x67, 0x68, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x46, 0x63, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x32, 0x52,
	0x09, 0x66, 0x63, 0x31, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x22, 0x2a, 0x0a, 0x09, 0x46, 0x63,
	0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x32, 0x12, 0x1d, 0x0a, 0x0a, 0x66, 0x63, 0x31, 0x5f, 0x77,
	0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x66, 0x63, 0x31,
	0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x22, 0x3b, 0x0a, 0x0c, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x57,
	0x65, 0x69, 0x67, 0x68, 0x74, 0x73, 0x12, 0x2b, 0x0a, 0x07, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x73, 0x2e, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x73, 0x52, 0x07, 0x77, 0x65, 0x69, 0x67,
	0x68, 0x74, 0x73, 0x22, 0x3c, 0x0a, 0x0d, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x57, 0x65, 0x69,
	0x67, 0x68, 0x74, 0x73, 0x12, 0x2b, 0x0a, 0x07, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73,
	0x2e, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x73, 0x52, 0x07, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74,
	0x73, 0x22, 0x1f, 0x0a, 0x0b, 0x50, 0x69, 0x6e, 0x67, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x63, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x63,
	0x6e, 0x74, 0x22, 0x1f, 0x0a, 0x0b, 0x50, 0x6f, 0x6e, 0x67, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03,
	0x63, 0x6e, 0x74, 0x22, 0x47, 0x0a, 0x10, 0x41, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x6f,
	0x72, 0x50, 0x49, 0x44, 0x4d, 0x73, 0x67, 0x12, 0x33, 0x0a, 0x0d, 0x41, 0x67, 0x67, 0x72, 0x65,
	0x67, 0x61, 0x74, 0x6f, 0x72, 0x50, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d,
	0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x50, 0x49, 0x44, 0x52, 0x0d, 0x41,
	0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x6f, 0x72, 0x50, 0x49, 0x44, 0x22, 0x4d, 0x0a, 0x18,
	0x4f, 0x74, 0x68, 0x65, 0x72, 0x43, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x50, 0x49, 0x44, 0x4d, 0x73, 0x67, 0x12, 0x31, 0x0a, 0x0c, 0x4f, 0x74, 0x68, 0x65,
	0x72, 0x43, 0x6f, 0x6d, 0x6d, 0x50, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d,
	0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x50, 0x49, 0x44, 0x52, 0x0c, 0x4f,
	0x74, 0x68, 0x65, 0x72, 0x43, 0x6f, 0x6d, 0x6d, 0x50, 0x49, 0x44, 0x22, 0x4e, 0x0a, 0x03, 0x50,
	0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x0e, 0x0a, 0x02,
	0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x22, 0x0c, 0x0a, 0x0a, 0x50,
	0x6f, 0x69, 0x73, 0x6f, 0x6e, 0x50, 0x69, 0x6c, 0x6c, 0x22, 0x3b, 0x0a, 0x12, 0x44, 0x65, 0x61,
	0x64, 0x4c, 0x65, 0x74, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x25, 0x0a, 0x06, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0d, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x50, 0x49, 0x44, 0x52, 0x06,
	0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x22, 0x30, 0x0a, 0x05, 0x57, 0x61, 0x74, 0x63, 0x68, 0x12,
	0x27, 0x0a, 0x07, 0x57, 0x61, 0x74, 0x63, 0x68, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0d, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x50, 0x49, 0x44, 0x52,
	0x07, 0x57, 0x61, 0x74, 0x63, 0x68, 0x65, 0x72, 0x22, 0x32, 0x0a, 0x07, 0x55, 0x6e, 0x77, 0x61,
	0x74, 0x63, 0x68, 0x12, 0x27, 0x0a, 0x07, 0x57, 0x61, 0x74, 0x63, 0x68, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e,
	0x50, 0x49, 0x44, 0x52, 0x07, 0x57, 0x61, 0x74, 0x63, 0x68, 0x65, 0x72, 0x22, 0x5b, 0x0a, 0x0a,
	0x54, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x64, 0x12, 0x1f, 0x0a, 0x03, 0x77, 0x68,
	0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x73, 0x2e, 0x50, 0x49, 0x44, 0x52, 0x03, 0x77, 0x68, 0x6f, 0x12, 0x2c, 0x0a, 0x03, 0x57,
	0x68, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x73, 0x2e, 0x54, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x64, 0x52, 0x65,
	0x61, 0x73, 0x6f, 0x6e, 0x52, 0x03, 0x57, 0x68, 0x79, 0x22, 0x06, 0x0a, 0x04, 0x53, 0x74, 0x6f,
	0x70, 0x22, 0x07, 0x0a, 0x05, 0x54, 0x6f, 0x75, 0x63, 0x68, 0x22, 0x2a, 0x0a, 0x07, 0x54, 0x6f,
	0x75, 0x63, 0x68, 0x65, 0x64, 0x12, 0x1f, 0x0a, 0x03, 0x77, 0x68, 0x6f, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x50, 0x49,
	0x44, 0x52, 0x03, 0x77, 0x68, 0x6f, 0x2a, 0x44, 0x0a, 0x10, 0x54, 0x65, 0x72, 0x6d, 0x69, 0x6e,
	0x61, 0x74, 0x65, 0x64, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x74,
	0x6f, 0x70, 0x70, 0x65, 0x64, 0x10, 0x00, 0x12, 0x15, 0x0a, 0x11, 0x41, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x54, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x64, 0x10, 0x01, 0x12, 0x0c,
	0x0a, 0x08, 0x4e, 0x6f, 0x74, 0x46, 0x6f, 0x75, 0x6e, 0x64, 0x10, 0x02, 0x32, 0x40, 0x0a, 0x06,
	0x50, 0x6f, 0x6e, 0x67, 0x65, 0x72, 0x12, 0x36, 0x0a, 0x04, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x15,
	0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x15, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73,
	0x2e, 0x50, 0x6f, 0x6e, 0x67, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x00, 0x42, 0x0f,
	0x5a, 0x0d, 0x74, 0x65, 0x73, 0x74, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_proto_rawDescOnce sync.Once
	file_protos_proto_rawDescData = file_protos_proto_rawDesc
)

func file_protos_proto_rawDescGZIP() []byte {
	file_protos_proto_rawDescOnce.Do(func() {
		file_protos_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_proto_rawDescData)
	})
	return file_protos_proto_rawDescData
}

var file_protos_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protos_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_protos_proto_goTypes = []interface{}{
	(TerminatedReason)(0),            // 0: messages.TerminatedReason
	(*Weights)(nil),                  // 1: messages.Weights
	(*Conv1Weight)(nil),              // 2: messages.Conv1Weight
	(*Conv1Weight2)(nil),             // 3: messages.Conv1Weight2
	(*Conv1Weight3)(nil),             // 4: messages.Conv1Weight3
	(*FcWeight)(nil),                 // 5: messages.FcWeight
	(*FcWeight2)(nil),                // 6: messages.FcWeight2
	(*LocalWeights)(nil),             // 7: messages.LocalWeights
	(*RemoteWeights)(nil),            // 8: messages.RemoteWeights
	(*PingMessage)(nil),              // 9: messages.PingMessage
	(*PongMessage)(nil),              // 10: messages.PongMessage
	(*AggregatorPIDMsg)(nil),         // 11: messages.AggregatorPIDMsg
	(*OtherCommunicationPIDMsg)(nil), // 12: messages.OtherCommunicationPIDMsg
	(*PID)(nil),                      // 13: messages.PID
	(*PoisonPill)(nil),               // 14: messages.PoisonPill
	(*DeadLetterResponse)(nil),       // 15: messages.DeadLetterResponse
	(*Watch)(nil),                    // 16: messages.Watch
	(*Unwatch)(nil),                  // 17: messages.Unwatch
	(*Terminated)(nil),               // 18: messages.Terminated
	(*Stop)(nil),                     // 19: messages.Stop
	(*Touch)(nil),                    // 20: messages.Touch
	(*Touched)(nil),                  // 21: messages.Touched
}
var file_protos_proto_depIdxs = []int32{
	2,  // 0: messages.Weights.conv1_weight:type_name -> messages.Conv1Weight
	2,  // 1: messages.Weights.conv2_weight:type_name -> messages.Conv1Weight
	5,  // 2: messages.Weights.fc1_weight:type_name -> messages.FcWeight
	5,  // 3: messages.Weights.fc2_weight:type_name -> messages.FcWeight
	3,  // 4: messages.Conv1Weight.conv1_weight:type_name -> messages.Conv1Weight2
	4,  // 5: messages.Conv1Weight2.conv1_weight:type_name -> messages.Conv1Weight3
	6,  // 6: messages.FcWeight.fc1_weight:type_name -> messages.FcWeight2
	1,  // 7: messages.LocalWeights.weights:type_name -> messages.Weights
	1,  // 8: messages.RemoteWeights.weights:type_name -> messages.Weights
	13, // 9: messages.AggregatorPIDMsg.AggregatorPID:type_name -> messages.PID
	13, // 10: messages.OtherCommunicationPIDMsg.OtherCommPID:type_name -> messages.PID
	13, // 11: messages.DeadLetterResponse.Target:type_name -> messages.PID
	13, // 12: messages.Watch.Watcher:type_name -> messages.PID
	13, // 13: messages.Unwatch.Watcher:type_name -> messages.PID
	13, // 14: messages.Terminated.who:type_name -> messages.PID
	0,  // 15: messages.Terminated.Why:type_name -> messages.TerminatedReason
	13, // 16: messages.Touched.who:type_name -> messages.PID
	9,  // 17: messages.Ponger.Ping:input_type -> messages.PingMessage
	10, // 18: messages.Ponger.Ping:output_type -> messages.PongMessage
	18, // [18:19] is the sub-list for method output_type
	17, // [17:18] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_protos_proto_init() }
func file_protos_proto_init() {
	if File_protos_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Weights); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Conv1Weight); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Conv1Weight2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Conv1Weight3); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FcWeight); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FcWeight2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LocalWeights); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoteWeights); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PongMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AggregatorPIDMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OtherCommunicationPIDMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PoisonPill); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeadLetterResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Watch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Unwatch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Terminated); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Stop); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Touch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Touched); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_proto_goTypes,
		DependencyIndexes: file_protos_proto_depIdxs,
		EnumInfos:         file_protos_proto_enumTypes,
		MessageInfos:      file_protos_proto_msgTypes,
	}.Build()
	File_protos_proto = out.File
	file_protos_proto_rawDesc = nil
	file_protos_proto_goTypes = nil
	file_protos_proto_depIdxs = nil
}
